y.exceptions.RayTaskError(RuntimeError): ray::ImplicitFunc.train() (pid=305523, ip=192.168.0.10, actor_id=f32726fcc8cd50aeb21c14e001000000, repr=trainable_function)
  File "/home/loebbert/miniconda3/envs/dipect/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/home/loebbert/miniconda3/envs/dipect/lib/python3.10/site-packages/ray/air/_internal/util.py", line 98, in run
    self._ret = self._target(*self._args, **self._kwargs)
  File "/home/loebbert/miniconda3/envs/dipect/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
  File "/home/loebbert/miniconda3/envs/dipect/lib/python3.10/site-packages/ray/tune/trainable/function_trainable.py", line 248, in _trainable_func
    output = fn()
  File "/home/loebbert/projects/deepclustering/LMU_Master_Practical_SoSe24/practical/DeepClustering/DipECT/hyperparameteroptimization.py", line 66, in trainable_function
    dipect.fit_predict(dataset, labels)
  File "/home/loebbert/projects/deepclustering/LMU_Master_Practical_SoSe24/practical/DeepClustering/DipECT/dipect.py", line 1837, in fit_predict
    tree, autoencoder = _dipect(
  File "/home/loebbert/projects/deepclustering/LMU_Master_Practical_SoSe24/practical/DeepClustering/DipECT/dipect.py", line 1615, in _dipect
    dipect_module.fit(
  File "/home/loebbert/projects/deepclustering/LMU_Master_Practical_SoSe24/practical/DeepClustering/DipECT/dipect.py", line 1408, in fit
    loss.backward()
  File "/home/loebbert/miniconda3/envs/dipect/lib/python3.10/site-packages/torch/_tensor.py", line 525, in backward
    torch.autograd.backward(
  File "/home/loebbert/miniconda3/envs/dipect/lib/python3.10/site-packages/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/home/loebbert/miniconda3/envs/dipect/lib/python3.10/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/loebbert/miniconda3/envs/dipect/lib/python3.10/site-packages/torch/autograd/function.py", line 301, in apply
    return user_fn(self, *args)
  File "/home/loebbert/miniconda3/envs/dipect/lib/python3.10/site-packages/clustpy/deep/dipencoder.py", line 126, in backward
    X, X_proj, sorted_indices, projection_vector, modal_triangle, dip_value = ctx.saved_tensors
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [10]] is at version 4; expected version 3 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).